# Generated by Django 4.2.6 on 2024-11-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('Primero Medio A', 'Primero Medio A'), ('Primero Medio B', 'Primero Medio B'), ('Primero Medio C', 'Primero Medio C'), ('Primero Medio D', 'Primero Medio D'), ('Primero Medio E', 'Primero Medio E'), ('Segundo Medio A', 'Segundo Medio A'), ('Segundo Medio B', 'Segundo Medio B'), ('Segundo Medio C', 'Segundo Medio C'), ('Segundo Medio D', 'Segundo Medio D'), ('Segundo Medio E', 'Segundo Medio E'), ('Tercero Medio A', 'Tercero Medio A'), ('Tercero Medio B', 'Tercero Medio B'), ('Tercero Medio C', 'Tercero Medio C'), ('Tercero Medio D', 'Tercero Medio D'), ('Tercero Medio E', 'Tercero Medio E'), ('Cuarto Medio A', 'Cuarto Medio A'), ('Cuarto Medio B', 'Cuarto Medio B'), ('Cuarto Medio C', 'Cuarto Medio C'), ('Cuarto Medio D', 'Cuarto Medio D'), ('Cuarto Medio E', 'Cuarto Medio E')], max_length=150, verbose_name='Curso')),
                ('enable', models.BooleanField(default=True, null=True, verbose_name='Alumno Regular')),
                ('apoderado_suplente_dos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.apoderadosuplentedos', verbose_name='Apoderado Suplente 2')),
                ('apoderado_suplente_uno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.apoderadosuplenteuno', verbose_name='Apoderado Suplente 1')),
                ('apoderado_titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.apoderadotitular', verbose_name='Apoderado')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Pie',
                'verbose_name_plural': 'Pies',
            },
        ),
    ]
