# Generated by Django 4.2.6 on 2024-05-06 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_academico', models.CharField(choices=[('Educación Parvularia', 'Educación Parvularia'), ('Primer Ciclo Básico', 'Primer Ciclo Básico'), ('Segundo Ciclo Básico', 'Segundo Ciclo Básico')], max_length=100, verbose_name='Nivel Académico')),
                ('curso', models.CharField(choices=[('Pre-Kinder', 'Pre-Kinder'), ('Kinder', 'Kinder'), ('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto'), ('Quinto', 'Quinto'), ('Sexto', 'Sexto'), ('Séptimo', 'Séptimo'), ('Octavo', 'Octavo')], max_length=100, verbose_name='Curso')),
                ('letra_curso', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Letra')),
                ('enable', models.BooleanField(default=True, null=True, verbose_name='Alumno Regular')),
                ('ApoderadoSuplenteDos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.apoderadosuplentedos', verbose_name='Apoderado Suplente 2')),
                ('ApoderadoSuplenteUno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.apoderadosuplenteuno', verbose_name='Apoderado Suplente 1')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.apoderadotitular', verbose_name='Apoderado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Pie',
                'verbose_name_plural': 'Pies',
            },
        ),
    ]
