# Generated by Django 4.2.6 on 2024-11-07 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('cursos', models.CharField(choices=[('Primero Medio A', 'Primero Medio A'), ('Primero Medio B', 'Primero Medio B'), ('Primero Medio C', 'Primero Medio C'), ('Primero Medio D', 'Primero Medio D'), ('Primero Medio E', 'Primero Medio E'), ('Segundo Medio A', 'Segundo Medio A'), ('Segundo Medio B', 'Segundo Medio B'), ('Segundo Medio C', 'Segundo Medio C'), ('Segundo Medio D', 'Segundo Medio D'), ('Segundo Medio E', 'Segundo Medio E'), ('Tercero Medio A', 'Tercero Medio A'), ('Tercero Medio B', 'Tercero Medio B'), ('Tercero Medio C', 'Tercero Medio C'), ('Tercero Medio D', 'Tercero Medio D'), ('Tercero Medio E', 'Tercero Medio E'), ('Cuarto Medio A', 'Cuarto Medio A'), ('Cuarto Medio B', 'Cuarto Medio B'), ('Cuarto Medio C', 'Cuarto Medio C'), ('Cuarto Medio D', 'Cuarto Medio D'), ('Cuarto Medio E', 'Cuarto Medio E')], max_length=150, verbose_name='Curso Estudiante')),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('etnia', models.CharField(choices=[('No posee', 'No posee'), ('Aymara', 'Aymara'), ('Lickanantay', ' Lickanantay'), ('Colla', 'Colla'), ('Quechua', 'Quechua'), ('Diaguita', 'Diaguita'), ('Chango', 'Chango'), ('Rapa Nui', 'Rapa Nui'), ('Mapuche', 'Mapuche'), ('Kawesqar', 'Kawesqar'), ('Yagan', 'Yagan')], default='No Posee', max_length=100, verbose_name='Ascendencia')),
                ('comorbilidad', models.TextField(verbose_name='Comorbilidad')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.comuna', verbose_name='Comuna')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='ApoderadoTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('etnia', models.CharField(blank=True, choices=[('No posee', 'No posee'), ('Aymara', 'Aymara'), ('Lickanantay', ' Lickanantay'), ('Colla', 'Colla'), ('Quechua', 'Quechua'), ('Diaguita', 'Diaguita'), ('Chango', 'Chango'), ('Rapa Nui', 'Rapa Nui'), ('Mapuche', 'Mapuche'), ('Kawesqar', 'Kawesqar'), ('Yagan', 'Yagan')], default='No Posee', max_length=100, null=True, verbose_name='Ascendencia')),
                ('salud', models.CharField(blank=True, choices=[('Seleccione', 'Seleccione'), ('Publica', 'Publica'), ('Privada', 'Privada')], default='Seleccione', max_length=100, null=True, verbose_name='Salud')),
                ('renta', models.PositiveIntegerField(blank=True, null=True, verbose_name='Renta')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.comuna', verbose_name='Comuna')),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Apoderado Titular',
                'verbose_name_plural': 'Apoderados Titulares',
            },
        ),
        migrations.CreateModel(
            name='ApoderadoSuplenteUno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.comuna', verbose_name='Comuna')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Apoderado Suplente Uno',
                'verbose_name_plural': 'Apoderados Suplentes Uno',
            },
        ),
        migrations.CreateModel(
            name='ApoderadoSuplenteDos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.comuna', verbose_name='Comuna')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante', verbose_name='Estudiante')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Apoderado Suplente Dos',
                'verbose_name_plural': 'Apoderados Suplentes Dos',
            },
        ),
    ]
