# Generated by Django 4.2.6 on 2024-05-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_apoderadosuplentedos_nombres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderadosuplentedos',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='apoderadosuplenteuno',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='apoderadotitular',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='Rut'),
        ),
    ]
